#!/usr/bin/perl
# Copyright (c) 2016 Trinity College, Dublin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

use warnings;
use strict;
use utf8;

binmode(STDIN, ":utf8");
binmode(STDOUT, ":utf8");

my $mtversion = 1;

while(<>) {
    s!<n>1\. S\.a\. </n><s>!<n>1. </n><a>S.a. </a><s>!;
    s!<g>npl\. ~</g><b>a, </b>!<g>npl. </g><b>~a, </b>!;
    s!<g>npl\. ~</g><b>a</b>!<g>npl. </g><b>~a</b>!;
    s!<g>gpl\. ~</g>\)\.!<g>gpl. </g><b>~</b>).!;
    s!<b>( *[0-9]+\. *)</b>!<n>$1</n>!g;

    s!<trans><r>See </r></trans><s>([^<]*)</s>!<a>See </a><s>$1</s>!g;

    s!<g>pred\. a\. Lit</g>!<g>pred. a. </g><c>Lit</c>!;
    s!<g>\&amp; a\. Rom\. Hist</g>!<g>&amp; a.</g> <c>Rom. Hist</c>!;
    s!<g>Mth</g>!<c>Mth</c>!;
    s!<g>adv\. \&amp; conj\. Lit</g>!<g>adv. &amp; conj.</g> <c>Lit</c>!;
    s!<g>a1\. Rom\. Hist</g>!<g>a1. </g><c>Rom. Hist</c>!;
    s!<g>a3\. Adm</g>!<g>a3.</g> <c>Adm</c>!;
    s!<g>a3\. Ball</g>!<g>a3.</g> <c>Ball</c>!;
    s!<g>a3\. Biol</g>!<g>a3.</g> <c>Biol</c>!;
    s!<g>a3\. Bot</g>!<g>a3.</g> <c>Bot</c>!;
    s!<g>a3\. Ch</g>!<g>a3.</g> <c>Ch</c>!;
    s!<g>a3\. Com</g>!<g>a3.</g> <c>Com</c>!;
    s!<g>a3\. Fin</g>!<g>a3.</g> <c>Fin</c>!;
    s!<g>a3\. Geog</g>!<g>a3.</g> <c>Geog</c>!;
    s!<g>a3\. Geol</g>!<g>a3.</g> <c>Geol</c>!;
    s!<g>a3\. Golf</g>!<g>a3.</g> <c>Golf</c>!;
    s!<g>a3\. Gram</g>!<g>a3.</g> <c>Gram</c>!;
    s!<g>a3\. Her</g>!<g>a3.</g> <c>Her</c>!;
    s!<g>a3\. Hort</g>!<g>a3.</g> <c>Hort</c>!;
    s!<g>a3\. Jur</g>!<g>a3.</g> <c>Jur</c>!;
    s!<g>a3\. Ling</g>!<g>a3.</g> <c>Ling</c>!;
    s!<g>a3\. Lit</g>!<g>a3.</g> <c>Lit</c>!;
    s!<g>a3\. Log</g>!<g>a3.</g> <c>Log</c>!;
    s!<g>a3\. Metalw</g>!<g>a3.</g> <c>Metalw</c>!;
    s!<g>a3\. Mth</g>!<g>a3.</g> <c>Mth</c>!;
    s!<g>a3\. Mus</g>!<g>a3.</g> <c>Mus</c>!;
    s!<g>a3\. Ph</g>!<g>a3.</g> <c>Ph</c>!;
    s!<g>a3\. Phot</g>!<g>a3.</g> <c>Phot</c>!;
    s!<g>a3\. Psy</g>!<g>a3.</g> <c>Psy</c>!;
    s!<g>adv\. Lit</g>!<g>adv.</g> <c>Lit</c>!;
    s!<g>adv\. Mus</g>!<g>adv.</g> <c>Mus</c>!;
    s!<g>a1\. Anat</g>!<g>a1.</g> <c>Anat</c>!;
    s!<g>a1\. Anthr</g>!<g>a1.</g> <c>Anthr</c>!;
    s!<g>a1\. Arch</g>!<g>a1.</g> <c>Arch</c>!;
    s!<g>a1\. Art</g>!<g>a1.</g> <c>Art</c>!;
    s!<g>a1\. B</g>!<g>a1.</g> <c>B</c>!;
    s!<g>a1\. Biol</g>!<g>a1.</g> <c>Biol</c>!;
    s!<g>a1\. Bot</g>!<g>a1.</g> <c>Bot</c>!;
    s!<g>a1\. Ch</g>!<g>a1.</g> <c>Ch</c>!;
    s!<g>a1\. Com</g>!<g>a1.</g> <c>Com</c>!;
    s!<g>a1\. Const</g>!<g>a1.</g> <c>Const</c>!;
    s!<g>a1\. Dressm</g>!<g>a1.</g> <c>Dressm</c>!;
    s!<g>a1\. Ecc</g>!<g>a1.</g> <c>Ecc</c>!;
    s!<g>a1\. El</g>!<g>a1.</g> <c>El</c>!;
    s!<g>a1\. El.E</g>!<g>a1.</g> <c>El.E</c>!;
    s!<g>a1\. Fin</g>!<g>a1.</g> <c>Fin</c>!;
    s!<g>a1\. Geog</g>!<g>a1.</g> <c>Geog</c>!;
    s!<g>a1\. Geol</g>!<g>a1.</g> <c>Geol</c>!;
    s!<g>a1\. Geom</g>!<g>a1.</g> <c>Geom</c>!;
    s!<g>a1\. Gram</g>!<g>a1.</g> <c>Gram</c>!;
    s!<g>a1\. Her</g>!<g>a1.</g> <c>Her</c>!;
    s!<g>a1\. Hist</g>!<g>a1.</g> <c>Hist</c>!;
    s!<g>a1\. Ins</g>!<g>a1.</g> <c>Ins</c>!;
    s!<g>a1\. Jur</g>!<g>a1.</g> <c>Jur</c>!;
    s!<g>a1\. Knitting</g>!<g>a1.</g> <c>Knitting</c>!;
    s!<g>a1\. Ling</g>!<g>a1.</g> <c>Ling</c>!;
    s!<g>a1\. Lit</g>!<g>a1.</g> <c>Lit</c>!;
    s!<g>a1\. Mch</g>!<g>a1.</g> <c>Mch</c>!;
    s!<g>a1\. Meas</g>!<g>a1.</g> <c>Meas</c>!;
    s!<g>a1\. Mec</g>!<g>a1.</g> <c>Mec</c>!;
    s!<g>a1\. Mec.E</g>!<g>a1.</g> <c>Mec.E</c>!;
    s!<g>a1\. Med</g>!<g>a1.</g> <c>Med</c>!;
    s!<g>a1\. Mth</g>!<g>a1.</g> <c>Mth</c>!;
    s!<g>a1\. Mus</g>!<g>a1.</g> <c>Mus</c>!;
    s!<g>a1\. Nat.Hist</g>!<g>a1.</g> <c>Nat.Hist</c>!;
    s!<g>a1\. Ph</g>!<g>a1.</g> <c>Ph</c>!;
    s!<g>a1\. Phil</g>!<g>a1.</g> <c>Phil</c>!;
    s!<g>a1\. Phot</g>!<g>a1.</g> <c>Phot</c>!;
    s!<g>a1\. Physiol</g>!<g>a1.</g> <c>Physiol</c>!;
    s!<g>a1\. Pol</g>!<g>a1.</g> <c>Pol</c>!;
    s!<g>a1\. Pros</g>!<g>a1.</g> <c>Pros</c>!;
    s!<g>a1\. Rh</g>!<g>a1.</g> <c>Rh</c>!;
    s!<g>a1\. Sm.a</g>!<g>a1.</g> <c>Sm.a</c>!;
    s!<g>a1\. Surg</g>!<g>a1.</g> <c>Surg</c>!;
    s!<g>a1\. Th</g>!<g>a1.</g> <c>Th</c>!;
    s!<g>a1\. Tls</g>!<g>a1.</g> <c>Tls</c>!;
    s!<g>a1\. Vet</g>!<g>a1.</g> <c>Vet</c>!;
    s!<g>a1\. W.Tel</g>!<g>a1.</g> <c>W.Tel</c>!;
    s!<g>a2\. Adm</g>!<g>a2.</g> <c>Adm</c>!;
    s!<g>a2\. Biol</g>!<g>a2.</g> <c>Biol</c>!;
    s!<g>a2\. Bot</g>!<g>a2.</g> <c>Bot</c>!;
    s!<g>a2\. Cer</g>!<g>a2.</g> <c>Cer</c>!;
    s!<g>a2\. Com</g>!<g>a2.</g> <c>Com</c>!;
    s!<g>a2\. Ling</g>!<g>a2.</g> <c>Ling</c>!;
    s!<g>a2\. Lit</g>!<g>a2.</g> <c>Lit</c>!;
    s!<g>a2\. Log</g>!<g>a2.</g> <c>Log</c>!;
    s!<g>a2\. Mth</g>!<g>a2.</g> <c>Mth</c>!;
    s!<g>a2\. Phil</g>!<g>a2.</g> <c>Phil</c>!;
    s!<g>a2\. Pol</g>!<g>a2.</g> <c>Pol</c>!;
    s!<g>a2\. Psy</g>!<g>a2.</g> <c>Psy</c>!;
    s!<g>gs\. as attrib\. a\. Fin</g>!<g>gs. as attrib. a.</g> <c>Fin</c>!;
    s!<g>gs\. as attrib\.a\. Jur</g>!<g>gs. as attrib.a.</g> <c>Jur</c>!;
    s!<g>gs\. as attrib\.a\. Lit</g>!<g>gs. as attrib.a.</g> <c>Lit</c>!;
    s!<g>gs\. as sttrib\. a\.</g>!<g>gs. as attrib. a.</g>!;
    s!<g>gs\. as a\. Phil</g>!<g>gs. as a.</g> <c>Phil</c>!;
    s!<g>gpl\. ~</g>!<g>gpl.</g> <b>~</b>!;
    s!<b>láith. gpl. ~</b>!<b>láith.</b> <g>gpl.</g> <b>~</b>!;
    s!<g>a1\. Insensible. </g>!<g>a1.</g> <trans><r>Insensible.</r></trans> !;
    s!<g>before article. S.a. </g>!<g>before article.</g> <a>S.a. </a>!;
    s!<g>Lenites\. S\.a\. </g>!<g>Lenites.</g> <a>S.a. </a>!;
    s!<g>vn. ~ f, gs. -</g><b>ála</b>!<g>vn.</g> <b>~</b> <g>f, gs. </g><b>-ála</b>!;
    s!<g>pred\. a\. used with copula\. Lit</g>!<g>pred. a. used with copula. </g><c>Lit</c>!;
    s!<g>pred\.a\. Lit</g>!<g>pred.a. </g><c>Lit</c>!;
    s!<g>pref\. Lit</g>!<g>pref. </g><c>Lit</c>!;
    s!<g>s\. El</g>!<g>s. </g><c>El</c>!;
    s!<g>s\. Jur</g>!<g>s. </g><c>Jur</c>!;
    s!<g>s\. Lit</g>!<g>s. </g><c>Lit</c>!;
    s!<g>s\. conj\. &amp; adv\. Lit</g>!<g>s. conj. &amp; adv. </g><c>Lit</c>!;
    s!<g>spl\. Artil</g>!<g>spl. </g><c>Artil</c>!;
    s!<g>spl\. Com</g>!<g>spl. </g><c>Com</c>!;
    s!<g>spl\. F</g>!<g>spl. </g><c>F</c>!;
    s!<g>spl\. Geol</g>!<g>spl. </g><c>Geol</c>!;
    s!<g>spl\. Jur</g>!<g>spl. </g><c>Jur</c>!;
    s!<g>spl\. Lit</g>!<g>spl. </g><c>Lit</c>!;
    s!<g>spl\. Mapm</g>!<g>spl. </g><c>Mapm</c>!;
    s!<g>spl\. Mec</g>!<g>spl. </g><c>Mec</c>!;
    s!<g>spl\. Myth</g>!<g>spl. </g><c>Myth</c>!;
    s!<g>spl\. Nau</g>!<g>spl. </g><c>Nau</c>!;
    s!<g>spl\. Th</g>!<g>spl. </g><c>Th</c>!;
    s!<g>suff\. Biol</g>!<g>suff. </g><c>Biol</c>!;
    s!<g>suff\. Ch</g>!<g>suff. </g><c>Ch</c>!;
    s!<g>v\.i\. Astr</g>!<g>v.i. </g><c>Astr</c>!;
    s!<g>v\.i\. Ch</g>!<g>v.i. </g><c>Ch</c>!;
    s!<g>v\.i\. El</g>!<g>v.i. </g><c>El</c>!;
    s!<g>v\.i\. Jur</g>!<g>v.i. </g><c>Jur</c>!;
    s!<g>v\.i\. Lit</g>!<g>v.i. </g><c>Lit</c>!;
    s!<g>v\.i\. Mec\.E</g>!<g>v.i. </g><c>Mec.E</c>!;
    s!<g>v\.i\. Phil</g>!<g>v.i. </g><c>Phil</c>!;
    s!<g>a1\. Log</g>!<g>a1. </g><c>Log</c>!;
    s!<g>v\.t\. &amp; i\. Biol</g>!<g>v.t. &amp; i. </g><c>Biol</c>!;
    s!<g>v\.t\. &amp; i\. Lit</g>!<g>v.t. &amp; i. </g><c>Lit</c>!;
    s!<g>v\.t\. &amp; i\. Metall</g>!<g>v.t. &amp; i. </g><c>Metall</c>!;
    s!<g>v\.t\. &amp; i\. Ph</g>!<g>v.t. &amp; i. </g><c>Ph</c>!;
    s!<g>v\.t\. &amp; i\. W\. Tel</g>!<g>v.t. &amp; i. </g><c>W.Tel</c>!;
    s!<g>v\.t\. Adm</g>!<g>v.t. </g><c>Adm</c>!;
    s!<g>v\.t\. Ar</g>!<g>v.t. </g><c>Ar</c>!;
    s!<g>v\.t\. Ch</g>!<g>v.t. </g><c>Ch</c>!;
    s!<g>v\.t\. Com</g>!<g>v.t. </g><c>Com</c>!;
    s!<g>v\.t\. Ecc</g>!<g>v.t. </g><c>Ecc</c>!;
    s!<g>v\.t\. El</g>!<g>v.t. </g><c>El</c>!;
    s!<g>v\.t\. Electronics</g>!<g>v.t. </g><c>Electronics</c>!;
    s!<g>v\.t\. Gram</g>!<g>v.t. </g><c>Gram</c>!;
    s!<g>v\.t\. Hort</g>!<g>v.t. </g><c>Hort</c>!;
    s!<g>v\.t\. Journ</g>!<g>v.t. </g><c>Journ</c>!;
    s!<g>v\.t\. Jur</g>!<g>v.t. </g><c>Jur</c>!;
    s!<g>v\.t\. Ling</g>!<g>v.t. </g><c>Ling</c>!;
    s!<g>v\.t\. Lit</g>!<g>v.t. </g><c>Lit</c>!;
    s!<g>v\.t\. Log</g>!<g>v.t. </g><c>Log</c>!;
    s!<g>v\.t\. Mec\.E</g>!<g>v.t. </g><c>Mec.E</c>!;
    s!<g>v\.t\. Metalw</g>!<g>v.t. </g><c>Metalw</c>!;
    s!<g>v\.t\. Mil</g>!<g>v.t. </g><c>Mil</c>!;
    s!<g>v\.t\. Mth</g>!<g>v.t. </g><c>Mth</c>!;
    s!<g>v\.t\. Mus</g>!<g>v.t. </g><c>Mus</c>!;
    s!<g>v\.t\. Ph</g>!<g>v.t. </g><c>Ph</c>!;
    s!<g>v\.t\. Phil</g>!<g>v.t. </g><c>Phil</c>!;
    s!<g>v\.t\. Psy</g>!<g>v.t. </g><c>Psy</c>!;
    s!<g>v\.t\. Th</g>!<g>v.t. </g><c>Th</c>!;
    s!<g>v\.t\. W\. Tel</g>!<g>v.t. </g><c>W.Tel</c>!;
    s!<g>v\.t\. W\.Tel</g>!<g>v.t. </g><c>W.Tel</c>!;
    # Partly included multiword in my version (removed because it was
    # counted as an example). As I don't have access to the full version, I
    # can't do anything here
    if($mtversion) {
	s!<h>ment\)\. </h>!!;
    }
    s!<title>aillt</title>\(<h>r\)eacha, </h>!<title>aillt(r)eacha, </title>!;
    s!<g>Lit</g>!<c>Lit</c>!;
    s!<a>S\.a\. \~smadra1 4</a>!<a>S.a. </a><s>madra</s><x>1</x> <n>4</n>!;
    s!<c>b</c>!<l>b</l>!;
    s!<c>e</c>!<l>e</l>!;
    s!<c>Conj\. </c>!<g>Conj. </g>!;
    s!<c>Dim\. of </c>!<g>Dim. of </g>!;
    s!<c>Pr\.n</c>!<g>Pr.n</g>!;
    s!<c>i</c>!<l>i</l>!;
    s!<c>lit</c>!<g>lit</g>!;
    s!</trans>\*\x7FbIn \~ linbh, <trans>!</trans><i>In ~ linbh</i><p>, </p><trans>!;
    s!<trans><r> picking bones, (ii) </r></trans>!<trans><r> picking bones</r></trans>, <r>(ii) </r>!;
    s!<r> Old, worn-out, horseshowe.</r>!<r>Old, worn-out, horseshoe.</r>!;
    s!</i>\)<p>!)</i><p>!;
    s!<l>II 1\(a</l>\)\.<p>!<r>II</r> <n>1</n>(<l>a</l>).<p>!;
    s!<l>I 1\(a</l>\)!<r>I</r> <n>1</n>(<l>a</l>)!;

    s!</n><r>\(Act of\) ([^<]*)</r>!</n><r>(Act of)</r> <trans><r>$1</r></trans>!;
    s!</b><r>\(Act of\) ([^<]*)</r>!</b><r>(Act of)</r> <trans><r>$1</r></trans>!;

    s!<r>\(Pet name and call name for a\) goose. </r>!<r>(Pet name and call name for a)</r> <trans><r>goose. </r></trans>!;
    s!<r> \(Pet name for\) lamb.</r>!<r> (Pet name for)</r> <trans><r>lamb.</r></trans>!;
    s!<r> \(Pet name and call name for\) pup, dog.</r>!<r> (Pet name and call name for)</r> <trans><r>pup, dog.</r></trans>!;
    s!<r> \(Pet name for\) hen. </r>!<r> (Pet name for)</r> <trans><r>hen. </r></trans>!;
    s!<r> \(Call-, pet-, name for\) calf.</r>!<r> (Call-, pet-, name for)</r> <trans><r>calf.</r></trans>!;
    s!<r>\(Call-name for\) cow.</r>!<r>(Call-name for)</r> <trans><r>cow.</r></trans>!;

    s!<r> \(House-\)cricket.</r>!<trans><r> (House-)cricket.</r></trans>!;
    s!<r> \(Nine\)pin. </r>!<trans><r> (Nine)pin. </r></trans>!;
    s!<r>\(Loud\) talk; disputation. </r>!<trans><r>(Loud) talk; disputation. </r></trans>!;
    s!<r> \(Shapeless\) bundle.</r>!<trans><r> (Shapeless) bundle.</r></trans>!;
    s!<r> \(Unnatural\) quarrelling.</r>!<trans><r> (Unnatural) quarrelling.</r></trans>!;
    s!<r> \(High\) ambition.</r>!<trans><r> (High) ambition.</r></trans>!;
    s!<r> \(Chief\) sovereignty.</r>!<trans><r> (Chief) sovereignty.</r></trans>!;
    s!<r> \(High\) esteem. </r>!<trans><r> (High) esteem. </r></trans>!;
    s!<r> \(Glow of\) raked embers.</r>!<trans><r> (Glow of) raked embers.</r></trans>!;
    s!<r>\(Land-\) steward.</r>!<trans><r>(Land-) steward.</r></trans>!;
    s!<r> \(Remnants of\) last year's turf. </r>!<trans><r> (Remnants of) last year's turf. </r></trans>!;
    s!<r>\(Stalk of\) water-lily. </r>!<trans><r>(Stalk of) water-lily. </r></trans>!;
    s!<r>\(Newly-\)baptized person. </r>!<trans><r>(Newly-)baptized person. </r></trans>!;
    s!<r> \(Small\) bank (of earth).</r>!<trans><r> (Small) bank (of earth).</r></trans>!;
    s!<r>\(Small\) bank. </r>!<trans><r>(Small) bank. </r></trans>!;
    s!<r> \(Suction\) pump.</r>!<trans><r> (Suction) pump.</r></trans>!;
    s!<r> \(Shepherd's\) crook. </r>!<trans><r> (Shepherd's) crook. </r></trans>!;
    s!<r> \(Snub\) nose. </r>!<trans><r> (Snub) nose. </r></trans>!;
    s!<r>\(Grooved valve of\) scallop-shell. </r>!<trans><r>(Grooved valve of) scallop-shell. </r></trans>!;
    s!<r> \(Point of\) abutment. </r>!<trans><r> (Point of) abutment. </r></trans>!;
    s!<r>\(Ancient\) stone fort. </r>!<trans><r>(Ancient) stone fort. </r></trans>!;
    s!<r> \(Dried\) cow-dung. </r>!<trans><r> (Dried) cow-dung. </r></trans>!;
    s!<r>\(Bald\) head.</r>!<trans><r>(Bald) head.</r></trans>!;
    s!<r> \(Hare's\) couch.</r>!<trans><r> (Hare's) couch.</r></trans>!;
    s!<r> \(First\) strip in ploughing; central strip of potato-ridge.</r>!<trans><r> (First) strip in ploughing; central strip of potato-ridge.</r></trans>!;
    s!<r>\(Hard\) palate. </r>!<trans><r>(Hard) palate. </r></trans>!;
    s!<r>\(Shower of\) hail. </r>!<trans><r>(Shower of) hail. </r></trans>!;
    s!<r>\(Spanish, sweet\) chestnut. </r>!<trans><r>(Spanish, sweet) chestnut. </r></trans>!;
    s!<r> \(Troops in\) battle order.</r>!<trans><r> (Troops in) battle order.</r></trans>!;
    s!<r>\(Small\) heap, mound. </r>!<trans><r>(Small) heap, mound. </r></trans>!;
    s!<r> \(Ancient\) churchyard. </r>!<trans><r> (Ancient) churchyard. </r></trans>!;
    s!<r> \(Stray\) blade of straw; </r>!<trans><r> (Stray) blade of straw; </r></trans>!;
    s!<r>\(Scarlet\) cloak. </r>!<trans><r>(Scarlet) cloak. </r></trans>!;
    s!<r> \(Astronomical\) cycle.</r>!<trans><r> (Astronomical) cycle.</r></trans>!;
    s!<r>\(Wool-\) comber; fuller. </r>!<trans><r>(Wool-) comber; fuller. </r></trans>!;
    s!<r> \(Wooden\) mug. </r>!<trans><r> (Wooden) mug. </r></trans>!;
    s!<r>\(Wicker\) basket. </r>!<trans><r>(Wicker) basket. </r></trans>!;
    s!<r> \(Field-\)fencing; low embankment. </r>!<trans><r> (Field-)fencing; low embankment. </r></trans>!;
    s!<r>\(Baby's\) napkin.</r>!<trans><r>(Baby's) napkin.</r></trans>!;
    s!<r> \(Small\) flame.</r>!<trans><r> (Small) flame.</r></trans>!;
    s!<r> \(Short\) rushes.</r>!<trans><r> (Short) rushes.</r></trans>!;
    s!<r>\(Ugly\) protuberance. </r>!<trans><r>(Ugly) protuberance. </r></trans>!;
    s!<r> \(Kind of\) limpet. </r>!<trans><r> (Kind of) limpet. </r></trans>!;
    s!<r> \(Thick\) lip.</r>!<trans><r> (Thick) lip.</r></trans>!;
    s!<r> \(Slight\) rash.</r>!<trans><r> (Slight) rash.</r></trans>!;
    s!<r>\(Small\) milking-place. </r>!<trans><r>(Small) milking-place. </r></trans>!;
    s!<r>\(Large, sacred\) tree. </r>!<trans><r>(Large, sacred) tree. </r></trans>!;
    s!<r> \(Boot\) blacking.</r>!<trans><r> (Boot) blacking.</r></trans>!;
    s!<r> \(Female\) stoat. </r>!<trans><r> (Female) stoat. </r></trans>!;
    s!<r>\(Glass\) float. </r>!<trans><r>(Glass) float. </r></trans>!;
    s!<r> \(Office of\) prime.</r>!<trans><r> (Office of) prime.</r></trans>!;
    s!<r> \(Faculty of\) invention.</r>!<trans><r> (Faculty of) invention.</r></trans>!;
    s!<r> \(Spoken\) hint.</r>!<trans><r> (Spoken) hint.</r></trans>!;
    s!<r>\(Made\) of beams.</r>!<trans><r>(Made) of beams.</r></trans>!;
    s!<r> \(Public\) crier. </r>!<trans><r> (Public) crier. </r></trans>!;
    s!<r> \(Small\) hurdle.</r>!<trans><r> (Small) hurdle.</r></trans>!;
    s!<r> \(Bell-\)ringer.</r>!<trans><r> (Bell-)ringer.</r></trans>!;
    s!<r> \(Small species of\) crab. </r>!<trans><r> (Small species of) crab. </r></trans>!;
    s!<r>\(Sheep\)fold.</r>!<trans><r>(Sheep)fold.</r></trans>!;
    s!<r> \(Outer\) edge, side; ledge. </r>!<trans><r> (Outer) edge, side; ledge. </r></trans>!;
    s!<r> \(Small\) sphere.</r>!<trans><r> (Small) sphere.</r></trans>!;
    s!<r> \(Process of\) condensation. </r>!<trans><r> (Process of) condensation. </r></trans>!;
    s!<r>\(Social\) company. </r>!<trans><r>(Social) company. </r></trans>!;
    s!<r> \(Lichen producing\) kind of purple dye.</r>!<trans><r> (Lichen producing) kind of purple dye.</r></trans>!;
    s!<r>\(Angular\) youth. </r>!<trans><r>(Angular) youth. </r></trans>!;
    s!<r> \(Quality of\) perseverance. </r>!<trans><r> (Quality of) perseverance. </r></trans>!;
    s!<r>\(Bodily\) sense. </r>!<trans><r>(Bodily) sense. </r></trans>!;
    s!<r>\(Corn-\)cockle; tares. </r>!<trans><r>(Corn-)cockle; tares. </r></trans>!;
    s!<r>\(Conical\) hive. </r>!<trans><r>(Conical) hive. </r></trans>!;
    s!<r> \(Standing-\)stone.</r>!<trans><r> (Standing-)stone.</r></trans>!;
    s!<r>\(Wedding-\)feast, banquet. </r>!<trans><r>(Wedding-)feast, banquet. </r></trans>!;
    s!<r> \(Sharp point, prickle, bristle.</r>!<trans><r> (Sharp point, prickle, bristle.</r></trans>!;
    s!<r> \(Little\) dove; pigeon. </r>!<trans><r> (Little) dove; pigeon. </r></trans>!;
    s!<r>\(Corresponding\) name. </r>!<trans><r>(Corresponding) name. </r></trans>!;
    s!<r> \(Corn-\)stalk; stubble.</r>!<trans><r> (Corn-)stalk; stubble.</r></trans>!;
    s!<r>\(Small\) roll, coil. </r>!<trans><r>(Small) roll, coil. </r></trans>!;
    s!<r>\(Angular\) youth. </r>!<trans><r>(Angular) youth. </r></trans>!;
    s!<r>\(Water\) plantain. </r>!<trans><r>(Water) plantain. </r></trans>!;
    s!<r> \(Boot-\) protector.</r>!<trans><r> (Boot-) protector.</r></trans>!;
    s!<r>\(Band of\) infantry.</r>!<trans><r>(Band of) infantry.</r></trans>!;
    s!<r>\(Furze\) chopper; cutter, slasher.</r>!<trans><r>(Furze) chopper; cutter, slasher.</r></trans>!;
    s!<r>\(Little\) claw. </r>!<trans><r>(Little) claw. </r></trans>!;
    s!<r>\(Fond of\) backbiting, gossiping.</r>!<trans><r>(Fond of) backbiting, gossiping.</r></trans>!;
    s!<r> \(Fit of\) lonesomeness; anxiety, sorrow. </r>!<trans><r> (Fit of) lonesomeness; anxiety, sorrow. </r></trans>!;
    s!<r> \(Shop\) counter.</r>!<trans><r> (Shop) counter.</r></trans>!;
    s!<r> \(Beggar's, traveller's\) wallet, scrip.</r>!<trans><r> (Beggar's, traveller's) wallet, scrip.</r></trans>!;
    s!<r> \(Small\) tub. </r>!<trans><r> (Small) tub. </r></trans>!;
    s!<r> \(Wooden\) oratory.</r>!<trans><r> (Wooden) oratory.</r></trans>!;
    s!<r> \(Small\) lump; hunk, chunk; portion, quantity. </r>!<trans><r> (Small) lump; hunk, chunk; portion, quantity. </r></trans>!;
    s!<r> \(Little\) foster-child; young pupil.</r>!<trans><r> (Little) foster-child; young pupil.</r></trans>!;
    s!<r> \(Bardic\) company; party, retinue. </r>!<trans><r> (Bardic) company; party, retinue. </r></trans>!;
    s!<r> \(Small\) bowl; cup.</r>!<trans><r> (Small) bowl; cup.</r></trans>!;
    s!<r>\(Small\) bundle. </r>!<trans><r>(Small) bundle. </r></trans>!;
    s!<r>\(Small\) bundle, ball. </r>!<trans><r>(Small) bundle, ball. </r></trans>!;
    s!<r> \(Small\) cavity. </r>!<trans><r> (Small) cavity. </r></trans>!;
    s!<r>\(Hoar-\)frost; frosty vapour. </r>!<trans><r>(Hoar-)frost; frosty vapour. </r></trans>!;
    s!<r>\(Stone indicating\) base in rounders. </r>!<trans><r>(Stone indicating) base in rounders. </r></trans>!;
    s!<r> \(Little\) oak.</r>!<trans><r> (Little) oak.</r></trans>!;
    s!<r> \(Little\) clod. </r>!<trans><r> (Little) clod. </r></trans>!;
    s!<r> \(Built-up\) heap. </r>!<trans><r> (Built-up) heap. </r></trans>!;
    s!<r> \(Article of\) hardware. </r>!<trans><r> (Article of) hardware. </r></trans>!;
    s!<r> \(Article of\) enamelware. </r>!<trans><r> (Article of) enamelware. </r></trans>!;
    s!<r>\(Small\) claw or hoof. </r>!<trans><r>(Small) claw or hoof. </r></trans>!;
    s!<r>\(Small\) hook or claw. </r>!<trans><r>(Small) hook or claw. </r></trans>!;
    s!<r>\(Little\) claw or hoof. </r>!<trans><r>(Little) claw or hoof. </r></trans>!;
    s!<r>\(Small\) harp. </r>!<trans><r>(Small) harp. </r></trans>!;
    s!<r>\(Of office, post\) Deanery.</r>!<trans><r>(Of office, post) Deanery.</r></trans>!;
    s!<r> \(Small\) hole, cavity.</r>!<trans><r> (Small) hole, cavity.</r></trans>!;
    s!<r> \(Species of\) pollock. </r>!<trans><r> (Species of) pollock. </r></trans>!;
    s!<r> \(Turning-\) lathe. </r>!<trans><r> (Turning-) lathe. </r></trans>!;
    s!<r>\(Pair of\) shears. </r>!<trans><r>(Pair of) shears. </r></trans>!;
    s!<r> \(John\) Dory. </r>!<trans><r> (John) Dory. </r></trans>!;
    s!<r> \(Small\) ear of corn.</r>!<trans><r> (Small) ear of corn.</r></trans>!;
    s!<r> \(State of\) orphanage.</r>!<trans><r> (State of) orphanage.</r></trans>!;
    s!<r> \(Vindicatory\) preface. </r>!<trans><r> (Vindicatory) preface. </r></trans>!;
    s!<r>\(Little\) wisp. </r>!<trans><r>(Little) wisp. </r></trans>!;
    s!<r>\(Illusory\) form, false appearance. </r>!<trans><r>(Illusory) form, false appearance. </r></trans>!;
    s!<r> \(Withered\) tree-stump.</r>!<trans><r> (Withered) tree-stump.</r></trans>!;
    s!<r> \(Railed-off\) chancel. </r>!<trans><r> (Railed-off) chancel. </r></trans>!;
    s!<r> \(Purple\) loosestrife.</r>!<trans><r> (Purple) loosestrife.</r></trans>!;
    s!<r> \(Dry\) morsel; undersized creature.</r>!<trans><r> (Dry) morsel; undersized creature.</r></trans>!;
    s!<r>\(Tiny-shelled\) dulse. </r>!<trans><r>(Tiny-shelled) dulse. </r></trans>!;
    s!<r> \(Pitted\) bog. </r>!<trans><r> (Pitted) bog. </r></trans>!;
    s!<r> \(Process of\) crystallization. </r>!<trans><r> (Process of) crystallization. </r></trans>!;
    s!<r>\(Small\) crock. </r>!<trans><r>(Small) crock. </r></trans>!;
    s!<r> \(Hat-, coat-, hall-\) stand. </r>!<trans><r> (Hat-, coat-, hall-) stand. </r></trans>!;
    s!<r> \(Boat\) sling.</r>!<trans><r> (Boat) sling.</r></trans>!;
    s!<r> \(Call-name for\) cow.</r>!<trans><r> (Call-name for) cow.</r></trans>!;
    s!<r>\(Large-\)hipped. </r>!<trans><r>(Large-)hipped. </r></trans>!;
    s!<r> \(Fisherman's\) gaff. </r>!<trans><r> (Fisherman's) gaff. </r></trans>!;
    s!<r>\(Small\) cross. </r>!<trans><r>(Small) cross. </r></trans>!;
    s!<r>\(Small\) stack. </r>!<trans><r>(Small) stack. </r></trans>!;
    s!<r> \(Kitchen\) sink. </r>!<trans><r> (Kitchen) sink. </r></trans>!;
    s!<r>\(State of\) burning. </r>!<trans><r>(State of) burning. </r></trans>!;
    s!<r>\(Small\) loop. </r>!<trans><r>(Small) loop. </r></trans>!;
    s!<r>\(Straw\) binding (on sheaf, leg of trousers). </r>!<trans><r>(Straw) binding (on sheaf, leg of trousers). </r></trans>!;
    s!<r> \(Small species of\) rock-fish, rockling. </r>!<trans><r> (Small species of) rock-fish, rockling. </r></trans>!;
    s!<r>\(Little\) lump. </r>!<trans><r>(Little) lump. </r></trans>!;
    s!<r>\(Fit of\) anger. </r>!<trans><r>(Fit of) anger. </r></trans>!;
    s!<r>\(Cord-\)line. </r>!<trans><r>(Cord-)line. </r></trans>!;
    s!<r>\(Small\) bush, tuft. </r>!<trans><r>(Small) bush, tuft. </r></trans>!;
    s!<r>\(Practice of\) magic. </r>!<trans><r>(Practice of) magic. </r></trans>!;
    s!<r>\(State of\) decay, decomposition; mustiness, mouldiness.</r>!<trans><r>(State of) decay, decomposition; mustiness, mouldiness.</r></trans>!;
    s!<r>\(Small\) bramble. </r>!<trans><r>(Small) bramble. </r></trans>!;
    s!<r> \(Little\) spark.</r>!<trans><r> (Little) spark.</r></trans>!;
    s!<r>\(Little\) curl; (little) lock, tuft. </r>!<trans><r>(Little) curl; (little) lock, tuft. </r></trans>!;
    s!<r>\(Little\) plait. </r>!<trans><r>(Little) plait. </r></trans>!;
    s!<r>\(Little\) fringe (of hair).</r>!<trans><r>(Little) fringe (of hair).</r></trans>!;
    s!<r> \(Fish-\)hook. </r>!<trans><r> (Fish-)hook. </r></trans>!;
    s!<r> \(Widow's\) dower.</r>!<trans><r> (Widow's) dower.</r></trans>!;
    s!<r>\(Late morning\) milking-time. </r>!<trans><r>(Late morning) milking-time. </r></trans>!;
    s!<r> \(State of\) extinction, death. </r>!<trans><r> (State of) extinction, death. </r></trans>!;
    s!<r> \(Ancient\) burial-ground. </r>!<trans><r> (Ancient) burial-ground. </r></trans>!;
    s!<r> \(Season of\) spring. </r>!<trans><r> (Season of) spring. </r></trans>!;
    s!<r> \(River-, ferry-\) boat; vessel. </r>!<trans><r> (River-, ferry-) boat; vessel. </r></trans>!;
    s!<r> \(Stick of\) barley sugar.</r>!<trans><r> (Stick of) barley sugar.</r></trans>!;
    s!<r> \(Small\) knot, lump. </r>!<trans><r> (Small) knot, lump. </r></trans>!;
    s!<r>\(Small\) lump. </r>!<trans><r>(Small) lump. </r></trans>!;
    s!<r> \(Baby's\) napkin; clout, rag.</r>!<trans><r> (Baby's) napkin; clout, rag.</r></trans>!;
    s!<r> \(Little\) sty; coop, pen; hovel. </r>!<trans><r> (Little) sty; coop, pen; hovel. </r></trans>!;
    s!<r>\(Hen's\) nest. </r>!<trans><r>(Hen's) nest. </r></trans>!;
    s!<r>\(Answering\) shout. </r>!<trans><r>(Answering) shout. </r></trans>!;
    s!<r> \(Little\) nest (for hen).</r>!<trans><r> (Little) nest (for hen).</r></trans>!;
    s!<r>\(Range of\) view, vision. </r>!<trans><r>(Range of) view, vision. </r></trans>!;
    s!<r>\(Small\) heap. </r>!<trans><r>(Small) heap. </r></trans>!;
    s!<r>\(Slight\) declivity, slope. </r>!<trans><r>(Slight) declivity, slope. </r></trans>!;
    s!<r> \(Eider-\)down.</r>!<trans><r> (Eider-)down.</r></trans>!;
    s!<r>\(Hen-\) roost. </r>!<trans><r>(Hen-) roost. </r></trans>!;
    s!<r>\(Combined segments of\) felloe. </r>!<trans><r>(Combined segments of) felloe. </r></trans>!;
    s!<r>\(Small\) weal, welt. </r>!<trans><r>(Small) weal, welt. </r></trans>!;
    s!<r> \(Small\) hind.</r>!<trans><r> (Small) hind.</r></trans>!;
    s!<r>\(Young\) warrior. </r>!<trans><r>(Young) warrior. </r></trans>!;
    s!<r> \(Wild\) iris, flag. </r>!<trans><r> (Wild) iris, flag. </r></trans>!;
    s!<r>\(Little\) tail. </r>!<trans><r>(Little) tail. </r></trans>!;
    s!<r>\(Small\) sinew; muscle. </r>!<trans><r>(Small) sinew; muscle. </r></trans>!;
    s!<r>\(Small\) vein. </r>!<trans><r>(Small) vein. </r></trans>!;
    s!<r> \(Kind of\) limpet. </r>!<trans><r> (Kind of) limpet. </r></trans>!;
    s!<r> \(Roving\) band of warriors. </r>!<trans><r> (Roving) band of warriors. </r></trans>!;
    s!<r> \(Fit of\) anger, petulance; huff. </r>!<trans><r> (Fit of) anger, petulance; huff. </r></trans>!;
    s!<r>\(Little\) chessman, pawn. </r>!<trans><r>(Little) chessman, pawn. </r></trans>!;
    s!<r> \(Small\) fold, tuck, plait.</r>!<trans><r> (Small) fold, tuck, plait.</r></trans>!;
    s!<r>\(Grape-\)vine. </r>!<trans><r>(Grape-)vine. </r></trans>!;
    s!<r> \(Wooden\) mouse-trap.</r>!<trans><r> (Wooden) mouse-trap.</r></trans>!;
    s!<r> \(Wood\) charcoal. </r>!<trans><r> (Wood) charcoal. </r></trans>!;
    s!<r> \(Section of\) felloe. </r>!<trans><r> (Section of) felloe. </r></trans>!;
    s!<r>\(Blood-\)red; bloody, sanguinary. </r>!<trans><r>(Blood-)red; bloody, sanguinary. </r></trans>!;
    s!<r>\(Drinking-\)feast. </r>!<trans><r>(Drinking-)feast. </r></trans>!;
    s!<r> \(Basement\) area. </r>!<trans><r> (Basement) area. </r></trans>!;
    s!<r>\(Well-\) sodded. </r>!<trans><r>(Well-) sodded. </r></trans>!;
    s!<r> \(Little\) sod, spot of ground.</r>!<trans><r> (Little) sod, spot of ground.</r></trans>!;
    s!<r> \(Small\) advertisement, poster.</r>!<trans><r> (Small) advertisement, poster.</r></trans>!;
    s!<r> \(Little strand of\) hair. </r>!<trans><r> (Little strand of) hair. </r></trans>!;
    s!<r> \(Art, trade, of\) building. </r>!<trans><r> (Art, trade, of) building. </r></trans>!;
    s!<r>\(Large\) measure, quantity. </r>!<trans><r>(Large) measure, quantity. </r></trans>!;
    s!<r> \(Fits of\) exuberance, spasmodic effort, fits and starts. </r>!<trans><r> (Fits of) exuberance, spasmodic effort, fits and starts. </r></trans>!;
    s!<r>\(Game of\) hide-and-seek.</r>!<trans><r>(Game of) hide-and-seek.</r></trans>!;
    s!<r>\(Tele\)phone.</r>!<trans><r>(Tele)phone.</r></trans>!;
    s!<r> \(Front of\) face, countenance; superficies, surface.</r>!<trans><r> (Front of) face, countenance; superficies, surface.</r></trans>!;
    s!<r> \(Work of\) supererogation.</r>!<trans><r> (Work of) supererogation.</r></trans>!;
    s!<r>\(Measuring-\)rod, pole. </r>!<trans><r>(Measuring-)rod, pole. </r></trans>!;
    s!<r>\(State of\) rest; stop, stay. </r>!<trans><r>(State of) rest; stop, stay. </r></trans>!;
    s!<r>\(Interior of\) wall. </r>!<trans><r>(Interior of) wall. </r></trans>!;
    s!<r>\(Deep-\)rootedness, inherence. </r>!<trans><r>(Deep-)rootedness, inherence. </r></trans>!;
    s!<r> \(Pulley-\)block.</r>!<trans><r> (Pulley-)block.</r></trans>!;
    s!<r> \(Frock-\)coat, jacket. </r>!<trans><r> (Frock-)coat, jacket. </r></trans>!;
    s!<r> \(Science of\) acoustics. </r>!<trans><r> (Science of) acoustics. </r></trans>!;
    s!<r> \(Kind of\) brooklime.</r>!<trans><r> (Kind of) brooklime.</r></trans>!;
    s!<r>\(Capacity for\) suffering; endurance, tolerance, forbearance. </r>!<trans><r>(Capacity for) suffering; endurance, tolerance, forbearance. </r></trans>!;
    s!<r>\(Cattle-\) pound. </r>!<trans><r>(Cattle-) pound. </r></trans>!;
    s!<r> \(White\) horse. </r>!<trans><r> (White) horse. </r></trans>!;
    s!<r>\(Small\) fork; forked stick; forked implement. </r>!<trans><r>(Small) fork; forked stick; forked implement. </r></trans>!;
    s!<r>\(Small\) grain of sand. </r>!<trans><r>(Small) grain of sand. </r></trans>!;
    s!<r>\(Warlike\) ardour; valour, fury. </r>!<trans><r>(Warlike) ardour; valour, fury. </r></trans>!;
    s!<r>\(Wooded\) river-valley; river-bed.</r>!<trans><r>(Wooded) river-valley; river-bed.</r></trans>!;
    s!<r> \(Certain species of\) large sea-fish (cod, hake, ling, pollock, etc.).</r>!<trans><r> (Certain species of) large sea-fish (cod, hake, ling, pollock, etc.).</r></trans>!;
    s!<r> \(Three-spined\) stickleback.</r>!<trans><r> (Three-spined) stickleback.</r></trans>!;
    s!<r> \(Small\) stalk, sprig; peduncle.</r>!<trans><r> (Small) stalk, sprig; peduncle.</r></trans>!;
    s!<r> \(Band of\) young warriors; band of \(young\) men, of soldiers. </r>!<trans><r> (Band of) young warriors; band of (young) men, of soldiers. </r></trans>!;
    s!<r>\(Short\) run, \(quick\) trip, \(hurried\) spell of activity. </r>!<trans><r>(Short) run, (quick) trip, (hurried) spell of activity. </r></trans>!;
    s!<r> \(Common\) tern, sea swallow. </r>!<trans><r> (Common) tern, sea swallow. </r></trans>!;
    s!<r>\(Bare\) patch. </r>!<trans><r>(Bare) patch. </r></trans>!;
    s!<r>\(Small\) branch, limb; appendage. </r>!<trans><r>(Small) branch, limb; appendage. </r></trans>!;
    s!<r> \(Gang of\) wild, mischievous, children. </r>!<trans><r> (Gang of) wild, mischievous, children. </r></trans>!;
    s!<r> \(Long\) rush. </r>!<trans><r> (Long) rush. </r></trans>!;
    s!<r> \(Wick of\) rush candle. </r>!<trans><r> (Wick of) rush candle. </r></trans>!;
    s!<r>\(Small\) missile. </r>!<trans><r>(Small) missile. </r></trans>!;
    s!<r>\(Small\) buttock(s); tail-end, rump. </r>!<trans><r>(Small) buttock(s); tail-end, rump. </r></trans>!;
    s!<r> \(Cooling\) fan.</r>!<trans><r> (Cooling) fan.</r></trans>!;
    s!<r> \(Uncut\) nap. </r>!<trans><r> (Uncut) nap. </r></trans>!;
    s!<r> \(Study of\) genealogy. </r>!<trans><r> (Study of) genealogy. </r></trans>!;
    s!<r> \(Procured\) abortion. </r>!<trans><r> (Procured) abortion. </r></trans>!;
    s!<r> \(Edible\) sea snail, winkle. </r>!<trans><r> (Edible) sea snail, winkle. </r></trans>!;
    s!<r>\(Divine\) mystery. </r>!<trans><r>(Divine) mystery. </r></trans>!;
    s!<r>\(Divinely\) mysterious. </r>!<trans><r>(Divinely) mysterious. </r></trans>!;
    s!<r> \(Iron\) bell.</r>!<trans><r> (Iron) bell.</r></trans>!;
    s!<r> \(Coarse kind of\) limpet.</r>!<trans><r> (Coarse kind of) limpet.</r></trans>!;
    s!<r>\(Small\) lobster. </r>!<trans><r>(Small) lobster. </r></trans>!;
    s!<r>\(Big-\)kneed; noded, nodulous. </r>!<trans><r>(Big-)kneed; noded, nodulous. </r></trans>!;
    s!<r> \(Disease marked by\) swelling in knees. </r>!<trans><r> (Disease marked by) swelling in knees. </r></trans>!;
    s!<r>\(Big-\)kneed.</r>!<trans><r>(Big-)kneed.</r></trans>!;
    s!<r>\(Small\) tip, point. </r>!<trans><r>(Small) tip, point. </r></trans>!;
    s!<r> \(Child's name for\) egg. </r>!<trans><r> (Child's name for) egg. </r></trans>!;
    s!<r>\(Small\) inlet, creek. </r>!<trans><r>(Small) inlet, creek. </r></trans>!;
    s!<r> \(Mortally\) wound; slay. </r>!<trans><r> (Mortally) wound; slay. </r></trans>!;
    s!<r> \(Fit of\) weeping; wail, lament. </r>!<trans><r> (Fit of) weeping; wail, lament. </r></trans>!;
    s!<r> \(Piece of\) slow, sad, music. </r>!<trans><r> (Piece of) slow, sad, music. </r></trans>!;
    s!<r> \(Scorching and\) grubbing of \(moor\)land.</r>!<trans><r> (Scorching and) grubbing of (moor)land.</r></trans>!;
    s!<r> \(Grubbing-\) hoe; grub-axe, scuffle-hoe. </r>!<trans><r> (Grubbing-) hoe; grub-axe, scuffle-hoe. </r></trans>!;
    s!<r> \(Small\) hoe.</r>!<trans><r> (Small) hoe.</r></trans>!;
    s!<r> \(Withered\) tree-stump. </r>!<trans><r> (Withered) tree-stump. </r></trans>!;
    s!<r> \(Mouth with\) prominent teeth. </r>!<trans><r> (Mouth with) prominent teeth. </r></trans>!;
    s!<r> \(Science of\) grammar. </r>!<trans><r> (Science of) grammar. </r></trans>!;
    s!<r> \(Act, art, of\) engraving.</r>!<trans><r> (Act, art, of) engraving.</r></trans>!;
    s!<r> \(Strip of\) raw meat; \(mass of\) raw flesh. </r>!<trans><r> (Strip of) raw meat; (mass of) raw flesh. </r></trans>!;
    s!<r>\(Upper part of\) cheek. </r>!<trans><r>(Upper part of) cheek. </r></trans>!;
    s!<r> \(Grassy\) verge.</r>!<trans><r> (Grassy) verge.</r></trans>!;
    s!<r> \(Ice-\)floe.</r>!<trans><r> (Ice-)floe.</r></trans>!;
    s!<r> \(Bride\)groom.</r>!<trans><r> (Bride)groom.</r></trans>!;
    s!<r> \(Stable\) groom.</r>!<trans><r> (Stable) groom.</r></trans>!;
    s!<r> \(Self-\)control, \(self-\)restraint. </r>!<trans><r> (Self-)control, (self-)restraint. </r></trans>!;
    s!<r>\(Coal-\)nuts. </r>!<trans><r>(Coal-)nuts. </r></trans>!;
    s!<r>\(Sharp-\)beaked.</r>!<trans><r>(Sharp-)beaked.</r></trans>!;
    s!<r> \(Child's name for\) young gull. </r>!<trans><r> (Child's name for) young gull. </r></trans>!;
    s!<r> \(Small\) hat, hood.</r>!<trans><r> (Small) hat, hood.</r></trans>!;
    s!<r> \(Scottish\) Highlander.</r>!<trans><r> (Scottish) Highlander.</r></trans>!;
    s!<r>\(Later\) descendant. </r>!<trans><r>(Later) descendant. </r></trans>!;
    s!<r>\(Resultant\) quarrel; row, disturbance. </r>!<trans><r>(Resultant) quarrel; row, disturbance. </r></trans>!;
    s!<r>\(Formal\) application. </r>!<trans><r>(Formal) application. </r></trans>!;
    s!<r> \(Trade, method, of\) fishing; fishery. </r>!<trans><r> (Trade, method, of) fishing; fishery. </r></trans>!;
    s!<r> \(Padded\) buffer.</r>!<trans><r> (Padded) buffer.</r></trans>!;
    s!<r> \(Assortment of\) edged weapons.</r>!<trans><r> (Assortment of) edged weapons.</r></trans>!;
    s!<r>\(All-round\) defence. </r>!<trans><r>(All-round) defence. </r></trans>!;
    s!<r> \(hypnotic\) suggestion.</r>!<trans><r> (hypnotic) suggestion.</r></trans>!;
    s!<r> \(Divine\) inspiration.</r>!<trans><r> (Divine) inspiration.</r></trans>!;
    s!<r> \(Lectern\) eagle.</r>!<trans><r> (Lectern) eagle.</r></trans>!;
    s!<r> \(Heathen\) temple.</r>!<trans><r> (Heathen) temple.</r></trans>!;
    s!<r> \(Act, game, of\) hurling.</r>!<trans><r> (Act, game, of) hurling.</r></trans>!;
    s!<r>\(Fond of\) wrestling; contentious.</r>!<trans><r>(Fond of) wrestling; contentious.</r></trans>!;
    s!<r>\(Fond of\) washing.</r>!<trans><r>(Fond of) washing.</r></trans>!;
    s!<r> \(Proper\) time, season, favourable opportunity. </r>!<trans><r> (Proper) time, season, favourable opportunity. </r></trans>!;
    s!<r> \(Great\) thirst; ardent desire, avidity. </r>!<trans><r> (Great) thirst; ardent desire, avidity. </r></trans>!;
    s!<r> \(Cattle-\)jobber. </r>!<trans><r> (Cattle-)jobber. </r></trans>!;
    s!<r> \(Bay\) laurel. </r>!<trans><r> (Bay) laurel. </r></trans>!;
    s!<r>\(Small\) toe, claw, fork, branch. </r>!<trans><r>(Small) toe, claw, fork, branch. </r></trans>!;
    s!<r> \(Moulding of\) reed.</r>!<trans><r> (Moulding of) reed.</r></trans>!;
    s!<r> \(Product of\) handcraft. </r>!<trans><r> (Product of) handcraft. </r></trans>!;
    s!<r> \(Act, art, of\) lance-fighting.</r>!<trans><r> (Act, art, of) lance-fighting.</r></trans>!;
    s!<r>\(Married or engaged\) couple. </r>!<trans><r>(Married or engaged) couple. </r></trans>!;
    s!<r>\(Young\) calf. </r>!<trans><r>(Young) calf. </r></trans>!;
    s!<r> \(Large\) vessel, ship.</r>!<trans><r> (Large) vessel, ship.</r></trans>!;
    s!<r> \(Cost of\) freightage.</r>!<trans><r> (Cost of) freightage.</r></trans>!;
    s!<r> \(Piece of\) rough, scrubby, ground. </r>!<trans><r> (Piece of) rough, scrubby, ground. </r></trans>!;
    s!<r>\(Bur of\) teasel. </r>!<trans><r>(Bur of) teasel. </r></trans>!;
    s!<r> \(Clothes-\)moth. </r>!<trans><r> (Clothes-)moth. </r></trans>!;
    s!<r> \(Medium-sized\) pollock.</r>!<trans><r> (Medium-sized) pollock.</r></trans>!;
    s!<r>\(Age of\) childhood. </r>!<trans><r>(Age of) childhood. </r></trans>!;
    s!<r> \(Pale\) ale; beer. </r>!<trans><r> (Pale) ale; beer. </r></trans>!;
    s!<r> \(Single\) cheek.</r>!<trans><r> (Single) cheek.</r></trans>!;
    s!<r> \(Act, art, of\) criticism.</r>!<trans><r> (Act, art, of) criticism.</r></trans>!;
    s!<r> \(Practice of\) medicine. </r>!<trans><r> (Practice of) medicine. </r></trans>!;
    s!<r> \(Line-\)drawing. </r>!<trans><r> (Line-)drawing. </r></trans>!;
    s!<r> \(Large\) coal-fish. </r>!<trans><r> (Large) coal-fish. </r></trans>!;
    s!<r> \(Act, practice, of\) fault-finding.</r>!<trans><r> (Act, practice, of) fault-finding.</r></trans>!;
    s!<r> \(Manual\) work, labour.</r>!<trans><r> (Manual) work, labour.</r></trans>!;
    s!<r>\(Small\) loop. </r>!<trans><r>(Small) loop. </r></trans>!;
    s!<r>\(Well-\)laden, well-filled. </r>!<trans><r>(Well-)laden, well-filled. </r></trans>!;
    s!<r> \(Hinged\) lid \(of side-table\). </r>!<trans><r> (Hinged) lid (of side-table). </r></trans>!;
    s!<r> \(Power of\) movement, agility; activity, vigour. </r>!<trans><r> (Power of) movement, agility; activity, vigour. </r></trans>!;
    s!<r> \(Edible part of\) shell-fish. </r>!<trans><r> (Edible part of) shell-fish. </r></trans>!;
    s!<r> \(Tuberous\) root. </r>!<trans><r> (Tuberous) root. </r></trans>!;
    s!<r> \(Square\) wooden drinking-cup, mether. </r>!<trans><r> (Square) wooden drinking-cup, mether. </r></trans>!;
    s!<r> \(Manx\) pony.</r>!<trans><r> (Manx) pony.</r></trans>!;
    s!<r> \(State of\) sorrow, lamentation.</r>!<trans><r> (State of) sorrow, lamentation.</r></trans>!;
    s!<r> \(Coastal\) sandbank; sand-hill, dune.</r>!<trans><r> (Coastal) sandbank; sand-hill, dune.</r></trans>!;
    s!<r> \(Little\) bleater; lamb, sheep.</r>!<trans><r> (Little) bleater; lamb, sheep.</r></trans>!;
    s!<r> \(Unwarranted\) suspicion.</r>!<trans><r> (Unwarranted) suspicion.</r></trans>!;
    s!<r>\(Eating of\) sweet things; sweetmeats, comfits. </r>!<trans><r>(Eating of) sweet things; sweetmeats, comfits. </r></trans>!;
    s!<r> \(Hunting of\) small game.</r>!<trans><r> (Hunting of) small game.</r></trans>!;
    s!<r> \(Little\) pinch, little bite, little bit. </r>!<trans><r> (Little) pinch, little bite, little bit. </r></trans>!;
    s!<r>\(Playing\) marble. </r>!<trans><r>(Playing) marble. </r></trans>!;
    s!<r>\(Right of\) turbary.</r>!<trans><r>(Right of) turbary.</r></trans>!;
    s!<r> \(Young, small\) wether. </r>!<trans><r> (Young, small) wether. </r></trans>!;
    s!<r>\(Child's name for\) grandmother.</r>!<trans><r>(Child's name for) grandmother.</r></trans>!;
    s!<r>\(Upper\) back. </r>!<trans><r>(Upper) back. </r></trans>!;
    s!<r> \(Bit of\) jetsam. </r>!<trans><r> (Bit of) jetsam. </r></trans>!;
    s!<r>\(The Virgin\) Mary. </r>!<trans><r>(The Virgin) Mary. </r></trans>!;
    s!<r>\(Vegetable-, leaf-\) mould, compost.</r>!<trans><r>(Vegetable-, leaf-) mould, compost.</r></trans>!;
    s!<r> \(Act, art, of\) moulding, modelling. </r>!<trans><r> (Act, art, of) moulding, modelling. </r></trans>!;
    s!<r> \(Do\) not. </r>!<trans><r> (Do) not. </r></trans>!;
    s!<r> \(Children's\) nursery.</r>!<trans><r> (Children's) nursery.</r></trans>!;
    s!<r> \(Use of\) adages, aphorisms; witticism, wisecracking. </r>!<trans><r> (Use of) adages, aphorisms; witticism, wisecracking. </r></trans>!;
    s!<r> Névé.</r>!<trans><r> Névé.</r></trans>!;
    s!<r> \(Ecological\) niche. </r>!<trans><r> (Ecological) niche. </r></trans>!;
    s!<r> \(Loud\) lamentation.</r>!<trans><r> (Loud) lamentation.</r></trans>!;
    s!<r>\(Sudden\) attempt. </r>!<trans><r>(Sudden) attempt. </r></trans>!;
    s!<r>\(Religious, funeral\) offering. </r>!<trans><r>(Religious, funeral) offering. </r></trans>!;
    s!<r> \(Art, practice, of\) ogham writing.</r>!<trans><r> (Art, practice, of) ogham writing.</r></trans>!;
    s!<r> \(State of\) manhood. </r>!<trans><r> (State of) manhood. </r></trans>!;
    s!<r> \(Gold\) filigree. </r>!<trans><r> (Gold) filigree. </r></trans>!;
    s!<r> \(Ceremonial\) washing of feet.</r>!<trans><r> (Ceremonial) washing of feet.</r></trans>!;
    s!<r>\(Supernatural\) power. </r>!<trans><r>(Supernatural) power. </r></trans>!;
    s!<r>\(Pustular\) swelling. </r>!<trans><r>(Pustular) swelling. </r></trans>!;
    s!<r> \(Turn\)pike. </r>!<trans><r> (Turn)pike. </r></trans>!;
    s!<r>\(Piece of\) coarse cloth. </r>!<trans><r>(Piece of) coarse cloth. </r></trans>!;
    s!<r>\(Fabulous\) beast, reptile, monster. </r>!<trans><r>(Fabulous) beast, reptile, monster. </r></trans>!;
    s!<r>\(Small\) worm. </r>!<trans><r>(Small) worm. </r></trans>!;
    s!<r> \(Act, art, of\) fencing. </r>!<trans><r> (Act, art, of) fencing. </r></trans>!;
    s!<r>\(Rounded\) cheek. </r>!<trans><r>(Rounded) cheek. </r></trans>!;
    s!<r> \(Nickname for\) chubby child. </r>!<trans><r> (Nickname for) chubby child. </r></trans>!;
    s!<r>\(Small\) pool. </r>!<trans><r>(Small) pool. </r></trans>!;
    s!<r> \(Cattle-\)pound. </r>!<trans><r> (Cattle-)pound. </r></trans>!;
    s!<r>\(State, ceremony, of\) marriage. </r>!<trans><r>(State, ceremony, of) marriage. </r></trans>!;
    s!<r>\(Timber\) post, stake. </r>!<trans><r>(Timber) post, stake. </r></trans>!;
    s!<r> \(Small\) pot. </r>!<trans><r> (Small) pot. </r></trans>!;
    s!<r> \(Little\) bounce, start, jump.</r>!<trans><r> (Little) bounce, start, jump.</r></trans>!;
    s!<r> \(Printing-\)press.</r>!<trans><r> (Printing-)press.</r></trans>!;
    s!<r> \(Small stone used as\) sinker.</r>!<trans><r> (Small stone used as) sinker.</r></trans>!;
    s!<r>\(Protruding\) mouth; sulky expression, pout. </r>!<trans><r>(Protruding) mouth; sulky expression, pout. </r></trans>!;
    s!<r> \(Rack-\)comb. </r>!<trans><r> (Rack-)comb. </r></trans>!;
    s!<r> \(Radio-active\) fall-out.</r>!<trans><r> (Radio-active) fall-out.</r></trans>!;
    s!<r> \(Most\) noble. </r>!<trans><r> (Most) noble. </r></trans>!;
    s!<r>\(Given to\) selling, vending, peddling. </r>!<trans><r>(Given to) selling, vending, peddling. </r></trans>!;
    s!<r>\(Small\) star. </r>!<trans><r>(Small) star. </r></trans>!;
    s!<r> \(Small\) star. </r>!<trans><r> (Small) star. </r></trans>!;
    s!<r>\(Fond of\) revelling, roistering.</r>!<trans><r>(Fond of) revelling, roistering.</r></trans>!;
    s!<r>\(Small\) star. </r>!<trans><r>(Small) star. </r></trans>!;
    s!<r>\(Euphemism for\) devil. </r>!<trans><r>(Euphemism for) devil. </r></trans>!;
    s!<r> \(Single\) hair. </r>!<trans><r> (Single) hair. </r></trans>!;
    s!<r>\(Dry-\)rotted; </r>!<trans><r>(Dry-)rotted; </r></trans>!;
    s!<r>\(Little\) wheel, circle; \(child's\) hoop. </r>!<trans><r>(Little) wheel, circle; (child's) hoop. </r></trans>!;
    s!<r>\(Small\) roll. </r>!<trans><r>(Small) roll. </r></trans>!;
    s!<r> \(Little\) roll. </r>!<trans><r> (Little) roll. </r></trans>!;
    s!<r> \(Versified\) legal maxim. </r>!<trans><r> (Versified) legal maxim. </r></trans>!;
    s!<r>\(Single\) hair. </r>!<trans><r>(Single) hair. </r></trans>!;
    s!<r> \(Religious\) mystery. </r>!<trans><r> (Religious) mystery. </r></trans>!;
    s!<r> \(Seine-\)net. </r>!<trans><r> (Seine-)net. </r></trans>!;
    s!<r> \(Flash of\) lightning. </r>!<trans><r> (Flash of) lightning. </r></trans>!;
    s!<r> \(Religious\) hypocrisy. </r>!<trans><r> (Religious) hypocrisy. </r></trans>!;
    s!<r>\(Fire-\) damper.</r>!<trans><r>(Fire-) damper.</r></trans>!;
    s!<r>\(Hot\) tea.</r>!<trans><r>(Hot) tea.</r></trans>!;
    s!<r>\(The\) cinema. </r>!<trans><r>(The) cinema. </r></trans>!;
    s!<r>\(Small\) crack, fissure. </r>!<trans><r>(Small) crack, fissure. </r></trans>!;
    s!<r> \(Small\) knock-kneed person.</r>!<trans><r> (Small) knock-kneed person.</r></trans>!;
    s!<r> \(Small\) crust, coating. </r>!<trans><r> (Small) crust, coating. </r></trans>!;
    s!<r> \(Slope covered with\) scree. </r>!<trans><r> (Slope covered with) scree. </r></trans>!;
    s!<r>\(Hand\)writing. </r>!<trans><r>(Hand)writing. </r></trans>!;
    s!<r>\(Little\) scratch. </r>!<trans><r>(Little) scratch. </r></trans>!;
    s!<r> \(Pilgrim's\) scrip.</r>!<trans><r> (Pilgrim's) scrip.</r></trans>!;
    s!<r> \(Iris of\) eye; glance.</r>!<trans><r> (Iris of) eye; glance.</r></trans>!;
    s!<r> \(Small\) rivet.</r>!<trans><r> (Small) rivet.</r></trans>!;
    s!<r> \(Wild\) honey-bee. </r>!<trans><r> (Wild) honey-bee. </r></trans>!;
    s!<r> \(Summons-\)server.</r>!<trans><r> (Summons-)server.</r></trans>!;
    s!<r> \(Navigation\) channel. </r>!<trans><r> (Navigation) channel. </r></trans>!;
    s!<r>\(Musical\) entertainment; pleasant diversion, amusement. </r>!<trans><r>(Musical) entertainment; pleasant diversion, amusement. </r></trans>!;
    s!<r> \(Bovine\) mastitis.</r>!<trans><r> (Bovine) mastitis.</r></trans>!;
    s!<r> \(Spinning-\)jenny.</r>!<trans><r> (Spinning-)jenny.</r></trans>!;
    s!<r>\(Festival\) straw garment.</r>!<trans><r>(Festival) straw garment.</r></trans>!;
    s!<r> \(Vertebrae of\) sacrum. </r>!<trans><r> (Vertebrae of) sacrum. </r></trans>!;
    s!<r> \(Science of\) hygiene.</r>!<trans><r> (Science of) hygiene.</r></trans>!;
    s!<r>\(Heap of\) soft material. </r>!<trans><r>(Heap of) soft material. </r></trans>!;
    s!<r> \(Ribwort\) plantain. </r>!<trans><r> (Ribwort) plantain. </r></trans>!;
    s!<r> \(act of\) lapping, swashing; splashing sound. </r>!<trans><r> (act of) lapping, swashing; splashing sound. </r></trans>!;
    s!<r>\(Many-\)sided; </r>!<trans><r>(Many-)sided; </r></trans>!;
    s!<r> \(Small\) shovelful.</r>!<trans><r> (Small) shovelful.</r></trans>!;
    s!<r>\(Sound of\) continuous splashing, swashing of water. </r>!<trans><r>(Sound of) continuous splashing, swashing of water. </r></trans>!;
    s!<r>\(Small\) spot, smudge. </r>!<trans><r>(Small) spot, smudge. </r></trans>!;
    s!<r> \(Black\)berry. </r>!<trans><r> (Black)berry. </r></trans>!;
    s!<r>\(Little\) black animal.</r>!<trans><r>(Little) black animal.</r></trans>!;
    s!<r>\(Small cloud of\) smoke, dust, vapour; misty haze. </r>!<trans><r>(Small cloud of) smoke, dust, vapour; misty haze. </r></trans>!;
    s!<r>\(Red\) marrow; pith, pulp. </r>!<trans><r>(Red) marrow; pith, pulp. </r></trans>!;
    s!<r>\(Single\) thread. </r>!<trans><r>(Single) thread. </r></trans>!;
    s!<r>\(Good\) omen, augury. </r>!<trans><r>(Good) omen, augury. </r></trans>!;
    s!<r>\(Abundance of\) good things. </r>!<trans><r>(Abundance of) good things. </r></trans>!;
    s!<r>\(Good, rich\) pickings; profit. </r>!<trans><r>(Good, rich) pickings; profit. </r></trans>!;
    s!<r>\(Little\) wisp; little bundle, handful, of straw, etc. </r>!<trans><r>(Little) wisp; little bundle, handful, of straw, etc. </r></trans>!;
    s!<r> \(Temperamental\) fit. </r>!<trans><r> (Temperamental) fit. </r></trans>!;
    s!<r>\(Fasten with\) bar, secure; batten. </r>!<trans><r>(Fasten with) bar, secure; batten. </r></trans>!;
    s!<r> \(Small\) spike.</r>!<trans><r> (Small) spike.</r></trans>!;
    s!<r>\(Furze-\)chopper made from section of scythe-blade. </r>!<trans><r>(Furze-)chopper made from section of scythe-blade. </r></trans>!;
    s!<r>\(Thunder-\)storm. </r>!<trans><r>(Thunder-)storm. </r></trans>!;
    s!<r> \(Monastic\) dispenser. </r>!<trans><r> (Monastic) dispenser. </r></trans>!;
    s!<r>\(Snow-\)flake. </r>!<trans><r>(Snow-)flake. </r></trans>!;
    s!<r> \(Small\) spark. </r>!<trans><r> (Small) spark. </r></trans>!;
    s!<r>\(Small\) twig; stick \(of firewood\). </r>!<trans><r>(Small) twig; stick (of firewood). </r></trans>!;
    s!<r> \(Small\) spring.</r>!<trans><r> (Small) spring.</r></trans>!;
    s!<r> \(Small\) bundle.</r>!<trans><r> (Small) bundle.</r></trans>!;
    s!<r>\(Small\) stream; rivulet, brook. </r>!<trans><r>(Small) stream; rivulet, brook. </r></trans>!;
    s!<r>\(Old\) gelding; old nag. </r>!<trans><r>(Old) gelding; old nag. </r></trans>!;
    s!<r> \(Little\) stallion.</r>!<trans><r> (Little) stallion.</r></trans>!;
    s!<r>\(Small\) projection; obstacle, obstruction. </r>!<trans><r>(Small) projection; obstacle, obstruction. </r></trans>!;
    s!<r> \(Small\) strip, slice; tatter.</r>!<trans><r> (Small) strip, slice; tatter.</r></trans>!;
    s!<r>\(Artistic\) style. </r>!<trans><r>(Artistic) style. </r></trans>!;
    s!<r> \(Little\) strip; piece stripped off sth.</r>!<trans><r> (Little) strip; piece stripped off sth.</r></trans>!;
    s!<r> \(Red\)berry. </r>!<trans><r> (Red)berry. </r></trans>!;
    s!<r>\(Sea\)-swell. </r>!<trans><r>(Sea)-swell. </r></trans>!;
    s!<r>\(Javelin-\) cord, amentum. </r>!<trans><r>(Javelin-) cord, amentum. </r></trans>!;
    s!<r> \(Billeted\) soldier.</r>!<trans><r> (Billeted) soldier.</r></trans>!;
    s!<r> \(Child's name for\) calf.</r>!<trans><r> (Child's name for) calf.</r></trans>!;
    s!<r>\(Little\) bubble, globule, bead. </r>!<trans><r>(Little) bubble, globule, bead. </r></trans>!;
    s!<r> \(Writing-\) tablet.</r>!<trans><r> (Writing-) tablet.</r></trans>!;
    s!<r>\(Stark\) naked. </r>!<trans><r>(Stark) naked. </r></trans>!;
    s!<r>\(Heat\) insulation.</r>!<trans><r>(Heat) insulation.</r></trans>!;
    s!<r>\(In the\) south. </r>!<trans><r>(In the) south. </r></trans>!;
    s!<r>\(In the\) west. </r>!<trans><r>(In the) west. </r></trans>!;
    s!<r>\(In the\) east. </r>!<trans><r>(In the) east. </r></trans>!;
    s!<r>\(In the\) north. </r>!<trans><r>(In the) north. </r></trans>!;
    s!<r>\(Small\) posterior. </r>!<trans><r>(Small) posterior. </r></trans>!;
    s!<r>\(Small load carried in\) hip-sack. </r>!<trans><r>(Small load carried in) hip-sack. </r></trans>!;
    s!<r> \(Deed of\) conveyance.</r>!<trans><r> (Deed of) conveyance.</r></trans>!;
    s!<r> \(Story of\) sack, destruction. </r>!<trans><r> (Story of) sack, destruction. </r></trans>!;
    s!<r> \(Small\) scone, cake. </r>!<trans><r> (Small) scone, cake. </r></trans>!;
    s!<r> \(Irish\) shilling piece. </r>!<trans><r> (Irish) shilling piece. </r></trans>!;
    s!<r>\(Small\) clump, clod. </r>!<trans><r>(Small) clump, clod. </r></trans>!;
    s!<r> \(Vector\) cross product.</r>!<trans><r> (Vector) cross product.</r></trans>!;
    s!<r>\(Pair of\) trousers.</r>!<trans><r>(Pair of) trousers.</r></trans>!;
    s!<r> \(Wire\) file for papers.</r>!<trans><r> (Wire) file for papers.</r></trans>!;
    s!<r> \(Pilgrim's\) staff.</r>!<trans><r> (Pilgrim's) staff.</r></trans>!;
    s!<r>\(Academic\) robe. </r>!<trans><r>(Academic) robe. </r></trans>!;
    s!<r> \(Vivid\) green. </r>!<trans><r> (Vivid) green. </r></trans>!;
    s!<r>\(Vivid\) green, verdant.</r>!<trans><r>(Vivid) green, verdant.</r></trans>!;
    s!<r> \(Bout of\) infectious disease. </r>!<trans><r> (Bout of) infectious disease. </r></trans>!;

    s!, díol<x>1</x>!, <s>díol</s><x>1</x>!;
    s!, dar<x>3</x>, dár<x>1,2</x>!, <s>dar</s><x>3</x>, <s>dár</s><x>1,2</x>!;
    s!, dath<x>1</x>!, <s>dath</s><x>1</x>!;
    s!, líon<x>1</x>!, <s>líon</s><x>1</x>!;
    s!, amháin <n>!, <s>amháin</s> <n>!;
    s!, marbh<x>2</x>!, <s>marbh</s><x>2</x>!;
    s!, cleith<x>1</x>!, <s>cleith</s><x>1</x>!;

    s!<g>m. Bot</g>!<g>m.</g> <c>Bot</c>!;
    s!<g>m. Lit</g>!<g>m.</g> <c>Lit</c>!;
    s!<g>m. Orn</g>!<g>m.</g> <c>Orn</c>!;
    s!<g>m\. \(gs\. \(gs\. </g>!<g>m. (gs. </g>!;
    s!</r><g>\&amp; a1. Gram</g>!</r><g>&amp; a1.</g> <c>Gram</c>!;
    s!<g>4. </g>!<n>4. </n>!;
    # FIXME
    s!<g>1a. </g>!<n>1a. </n>!;
    s!<g>\&amp; a1\. Anat</g>!<g>&amp; a1.</g> <c>Anat</c>!;
    s!<trans><r>Used as consonant, e\.g\. </r></trans>!<r>Used as consonant, e.g. </r>!;
    s!<trans><r>Prefixed to initial vowel as aspirate, e\.g\. </r></trans>!<r>Prefixed to initial vowel as aspirate, e.g. </r>!;
    s!<trans><r>Used after </r></trans>!<r>Used after </r>!;
    s!<trans><r>to denote lenition, e\.g\. </r></trans>!<r>to denote lenition, e.g. </r>!;
    s!\(Eclipses, prefixes </r></trans>!</r></trans><r>(Eclipses, prefixes </r>!;
    s!<trans><r>to vowels\) </r></trans>!<r>to vowels) </r>!;
    s!\(Lenites\) </r></trans>!</r></trans><r>(Lenites) </r>!;
    s!<trans><r>before vowels or </r></trans>!<r>before vowels or </r>!;
    s!<trans><r>to vowels\) </r></trans>!<r>to vowels) </r>!;
    s!<g>particle used with abstract nouns denoting degree. \(Lenites</g>\)!<r>particle used with abstract nouns denoting degree. (Lenites)</r>!;
    s!\(As object of vn.</g>\)<r>!</g><r>(As object of vn.)</r><r>!;
    s!<g>Pron. \(Eclipses</g>\)!<g>Pron.</g> <r>(Eclipses)</r>!;
    s!Eclipses letter P, e.g. </r></trans>!</r></trans><r>Eclipses letter P, e.g. </r>!;
    s!<trans><r>to vowels\) </r></trans>!<r>to vowels) </r>!;
    s!\(Prefixes </r></trans>!</r></trans><r>(Prefixes </r>!;
    s!<trans><r>Used as consonant, e.g. </r></trans>!<r>Used as consonant, e.g. </r>!;
    s!<trans><r>Prefixed to initial vowel as aspirate, e.g. </r></trans>!<r>Prefixed to initial vowel as aspirate, e.g. </r>!;
    s!<trans><r>before vowels or </r></trans>!<r>before vowels or </r>!;
    s!<trans><r>to vowels\) </r></trans>!<r>to vowels) </r>!;
    s!<b>Tá a ~ \(beag</b>\)<r>!<i>Tá a ~ (beag)</i><r>!;
    s!<trans><r>Useful implement \(referring to fem. noun\)\. </r></trans>!<trans><r>Useful implement </r></trans><r>(referring to fem. noun). </r>!;

    s/  */ /g;

    print;
}
